
insert into MY_SCHEMA.ACCOUNT_TYPE (ACCOUNT_TYPE_ID, MNEMONIC, ACCOUNT_TYPE_NAME, CREATION_DATE)
values (50000, 'MiLES', 'Miles', TO_DATE('2020/01/01', 'YYYY/MM/DD'));
insert into MY_SCHEMA.ACCOUNT_TYPE (ACCOUNT_TYPE_ID, MNEMONIC, ACCOUNT_TYPE_NAME, CREATION_DATE)
values (50001, 'PLAY', 'Game Play', TO_DATE('2020/03/01', 'YYYY/MM/DD'));